# This is a config for E2B sandbox template.
# You can use template ID (ct67bz03e8tt5q809qtw) or template name (volt-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("volt-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("volt-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('volt-nextjs-test-2')

team_id = "77bcdd95-07a9-4289-9f0c-bd9eafa957de"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "volt-nextjs-test-2"
template_id = "ct67bz03e8tt5q809qtw"
